POST http://localhost:3333/users
content-type: application/json

{
    "name": "carla",
    "email": "testecarla@teste.com",
    "password": "12345678",
    "confirm_password": "12345678"
}

###

GET http://localhost:3333/users

###

GET http://localhost:3333/users/1
content-type: application/json

###

PUT http://localhost:3333/users/1
content-type: application/json

{
    "name": "carla",
    "email": "testecarla@teste.com",
    "password": "12345678",
    "confirm_password": "12345678"
}

###

DELETE http://localhost:3333/users/3

###
POST http://localhost:3333/thoughts
Content-Type: application/json

{
    "title": "Pensamento 01",
    "description": "Pensamento dp dia"
}

###

GET http://localhost:333/thoughts